### ISSUE TITLE
flagged as Win64:Malware-gen

### ISSUE THREAD

**Issue by john123903** [dhtdht020/osc-dl#120]
idk why, but it doesnt let me update bc of malware.... i wonder why.

**Comment by Naim2000** [comment]
Does it say !ml at the end

**Comment by dhtdht020** [comment]
False positive, and not enough information to do anything about this. What antivirus? Installer or program? On launch or during use?

**Comment by dhtdht020** [comment]
It seems like Avast and AVG which both had the `Win64:Malware-gen` flag have removed the label. There are still some false positives in VirusTotal, but from very unpopular antiviruses.

**Comment by john123903** [comment]
> It seems like Avast and AVG which both detected OSCDL as `Win64:Malware-gen` have corrected it and no longer do so. There are still some false positives in VirusTotal, but from very unpopular antiviruses.

Or security vendor if that’s ok

**Comment by john123903** [comment]
> It seems like Avast and AVG which both detected OSCDL as `Win64:Malware-gen` have corrected it and no longer do so. There are still some false positives in VirusTotal, but from very unpopular antiviruses.

And yes, I'm using Avast.
