### ISSUE TITLE
Problems found during first time use

### ISSUE THREAD

**Issue by DRKV333** [dhtdht020/osc-dl#15]
I've used the CLI tool to download a bunch of stuff in bulk, and ran into a few problems.

Normally, trying to download anything will crash with `TypeError: get() got an unexpected keyword argument 'type'` right here:
https://github.com/dhtdht020/osc-dl/blob/444ff0308f2cea09221456bc62e7986d66d52bf6/parsecontents.py#L147
Removing the extra `type` argument seems to fix the problem.

It also looks like the `get-list` command doesn't detect text encoding correctly. I first tried with UCS-2 LE BOM, but that kinda freaked it out. It worked after converting the file to ANSI.

After fixing these two issues, everything went flawlessly and I got my downloads.

**Comment by dhtdht020** [comment]
I'm very sorry for this, the CLI tool is no longer the primary focus, it's very poorly done and would be rewritten later on to use the new Open Shop Channel API rather than scraping it.

As for the issues you are having:
`Type` is a removed argument and it seems I forgot it mentioned in a few places. Thanks for letting me know, and this should be solved with commit 051e14c5.


The `get-list` command uses the Requests library to obtain host/metadata.json's contents and iterates over every item to get app names. I am not sure what is going wrong here. Can you clarify which host you used?

**Comment by DRKV333** [comment]
> The get-list command uses the Requests library to obtain host/metadata.json's contents and iterates over every item to get app names.

I think you're thinking of `list`. `get-list` downloads a set of items, specified in a file. I first got a full list of all items by doing:
```
py -3 .\osc-dl.py list --raw > testlist.txt
```
Then if I try using `get-list` with the `-d` option, to read this same file, I get this:
```
PS C:\Users\Vince\Documents\wiiuhax\osc\osc-dl> py -3 .\osc-dl.py get-list -f testlist.txt -d
ÿþ2 4 0 p S u i t e

 a b u s e

 A c h t u n g _ W i i _ K u r v e

 A n y G l o b e _ C h a n g e r

 b a l a n c e t o o l s

 B B P R O

 b l u e m s x - w i i

 B o o t M i i C o n f i g u r a t i o n E d i t o r

 b r a w l s t a t s

 c a l i b r a t o r

 c e r t _ s y s _ e x t r a c t o r

 C h e c k R e g i o n

 c h i p p y

 c i t y d e m o

 C l e a n R i p

 c o m p e t i t i o n - t o o l - w i i

 d 2 x - c i o s - i n s t a l l e r

 d c v g 5 k
```
And without the `-d` option it fails to download, since it reads the package names wrong:
```
PS C:\Users\Vince\Documents\wiiuhax\osc\osc-dl> py -3 .\osc-dl.py get-list -f testlist.txt
Searching for package on hbb1.oscwii.org..
Could not find "ÿþ2 4 0 p S u i t e " on the repository. :(
Searching for package on hbb1.oscwii.org..
Could not find " " on the repository. :(
Searching for package on hbb1.oscwii.org..
Could not find " a b u s e " on the repository. :(
Searching for package on hbb1.oscwii.org..
Could not find " " on the repository. :(
Searching for package on hbb1.oscwii.org..
Could not find " A c h t u n g _ W i i _ K u r v e " on the repository. :(
Searching for package on hbb1.oscwii.org..
Could not find " " on the repository. :(
```
It's simple fix on the user's part really. I'm sure the encoding of the output file in this case is dependent on what OS and shell is used. I did it on Windows with PowerShell. This exact scenario might work fine with other setups. It's just a bit of a weird gotcha to look out for.

**Comment by dhtdht020** [comment]
Thanks for clarifying, I will look into this.

**Comment by jaylawcote** [comment]
@dhtdht020

**Comment by dhtdht020** [comment]
Sorry for keeping this open for so long, but as the CLI is currently being rewritten, this issue is no longer relevant.
However, the problems shown here will be considered if this feature makes a return.
