### ISSUE TITLE
xosc_dl.py and osc-dl.py both result in exec: Exec format error

### ISSUE THREAD

**Issue by LaVie024** [dhtdht020/osc-dl#25]
Attempting to run either of these using ./ basically results in this error, then states that it is marked as an executable but could not be run by the operating system. Using the python3 command basically does nothing as well.

Using Debian Sid with Python 3.9.1+

**Comment by dhtdht020** [comment]
Both files do not have headers, which means you must run the file through python rather than directly.

**Comment by dhtdht020** [comment]
If this is a problem, you can resolve this by adding `#!/usr/bin/env python` to the first line of both files.
