### ISSUE TITLE
Avira detects application as HEUR/APC (Cloud)

### ISSUE THREAD

**Issue by Sukotto-1999** [dhtdht020/osc-dl#27]
I was going to download homebrew applications via the OSC-dl app, when i try to open it for the first time, instead of opening the application, Avira detects it containing the PATTERN of HEUR/APC and permanently stopped me from using the OSC-DL app

**Comment by dhtdht020** [comment]
This sounds like a false positive. Most antiviruses have an option to send a quarantined file for analysis, I recommend doing so. I cannot help any further, antivirus detection is beyond me.

**Comment by Sukotto-1999** [comment]
Thank you. i appreciate with that
