### ISSUE TITLE
Linux compatibility?

### ISSUE THREAD

**Issue by wuniversales** [dhtdht020/osc-dl#29]
In my case I have linux and I would like to use the program.
Thanks greetings

**Comment by dhtdht020** [comment]
Hello, Linux is indeed supported. Here are the instructions:

Make sure Python 3 is installed and used.

- Download the source from https://github.com/dhtdht020/osc-dl/releases/tag/1.2.10 (Do not directly git clone, master has a few issues on linux at the moment)
- Extract it
- pip3 install -r requirements_GUI.txt
- python3 xosc-dl.py
