### ISSUE TITLE
Stuck on 0% downloading when using "Send to Wii"

### ISSUE THREAD

**Issue by helpimnotdrowning** [dhtdht020/osc-dl#32]
When I select any app and download via "Send to Wii", the download gets stuck on "Downloading app from Open Shop Channel 0%", untill it dissapears by itself after clicking on the file buttons (About, Clients, Debug) or alt-tabbing. I'm getting the Wii's IP address from both the Homebrew channel and my router config page.

I have a sneaking suspicion that osc-dl might be using the wrong network adapter to try and connect to the Wii, since I have Virtualbox and WSL adapters installed, but I don't know much about how that works.

Using:
Windows 10 v20H2
OSC-DL v1.2.11

**Comment by dhtdht020** [comment]
This problem has been fixed, and I have updated the files in the release.
