### ISSUE TITLE
MacOS Support?

### ISSUE THREAD

**Issue by quimodotcom** [dhtdht020/osc-dl#40]

**Comment by dhtdht020** [comment]
macOS is supported.

**Comment by quimodotcom** [comment]
link to macOS binary?

**Comment by TheTechRobo** [comment]
run the python script yourself, there's no binary

**Comment by TheTechRobo** [comment]
there is only a Windows binary, but you can still run the scripts on macOS!

**Comment by quimodotcom** [comment]
cheers!
